// Карта логотипов брендов для Autobase
// Ключ должен совпадать с полем name в brands.js

const BRAND_LOGOS = {
  "Abarth": "https://cdn.simpleicons.org/abarth/white",
  "Acura": "https://cdn.simpleicons.org/acura/white",
  "Alfa Romeo": "https://cdn.simpleicons.org/alfaromeo/white",
  "Alpine": "https://cdn.simpleicons.org/alpine/white",
  "Aston Martin": "https://cdn.simpleicons.org/astonmartin/white",
  "Audi": "https://cdn.simpleicons.org/audi/white",
  "BAIC": "https://cdn.simpleicons.org/baic/white",
  "Bentley": "https://cdn.simpleicons.org/bentley/white",
  "BMW": "https://cdn.simpleicons.org/bmw/white",
  "Bugatti": "https://cdn.simpleicons.org/bugatti/white",
  "Buick": "https://cdn.simpleicons.org/buick/white",
  "BYD": "https://cdn.simpleicons.org/byd/white",
  "Cadillac": "https://cdn.simpleicons.org/cadillac/white",
  "Chevrolet": "https://cdn.simpleicons.org/chevrolet/white",
  "Chery": "https://cdn.simpleicons.org/chery/white",
  "Chrysler": "https://cdn.simpleicons.org/chrysler/white",
  "Citroen": "https://cdn.simpleicons.org/citroen/white",
  "Cupra": "https://cdn.simpleicons.org/cupra/white",
  "Dacia": "https://cdn.simpleicons.org/dacia/white",
  "Dodge": "https://cdn.simpleicons.org/dodge/white",
  "DS": "https://cdn.simpleicons.org/dsautomobiles/white",
  "DS Automobiles": "https://cdn.simpleicons.org/dsautomobiles/white",
  "Ferrari": "https://cdn.simpleicons.org/ferrari/white",
  "Fiat": "https://cdn.simpleicons.org/fiat/white",
  "Ford": "https://cdn.simpleicons.org/ford/white",
  "Genesis": "https://cdn.simpleicons.org/genesis/white",
  "Geely": "https://cdn.simpleicons.org/geely/white",
  "GMC": "https://cdn.simpleicons.org/gmc/white",
  "Great Wall": "https://cdn.simpleicons.org/greatwall/white",
  "Haval": "https://cdn.simpleicons.org/haval/white",
  "Honda": "https://cdn.simpleicons.org/honda/white",
  "Hongqi": "https://cdn.simpleicons.org/hongqi/white",
  "Hummer": "https://cdn.simpleicons.org/hummer/white",
  "Hyundai": "https://cdn.simpleicons.org/hyundai/white",
  "Infiniti": "https://cdn.simpleicons.org/infiniti/white",
  "Isuzu": "https://cdn.simpleicons.org/isuzu/white",
  "Jaguar": "https://cdn.simpleicons.org/jaguar/white",
  "Jeep": "https://cdn.simpleicons.org/jeep/white",
  "Jetour": "https://cdn.simpleicons.org/jetour/white",
  "Kia": "https://cdn.simpleicons.org/kia/white",
  "Koenigsegg": "https://cdn.simpleicons.org/koenigsegg/white",
  "Lada (ВАЗ)": "https://cdn.simpleicons.org/lada/white",
  "Lada": "https://cdn.simpleicons.org/lada/white",
  "Lamborghini": "https://cdn.simpleicons.org/lamborghini/white",
  "Lancia": "https://cdn.simpleicons.org/lancia/white",
  "Land Rover": "https://cdn.simpleicons.org/landrover/white",
  "Lexus": "https://cdn.simpleicons.org/lexus/white",
  "Li Auto": "https://cdn.simpleicons.org/liauto/white",
  "Lincoln": "https://cdn.simpleicons.org/lincoln/white",
  "Lotus": "https://cdn.simpleicons.org/lotus/white",
  "Maserati": "https://cdn.simpleicons.org/maserati/white",
  "Maybach": "https://cdn.simpleicons.org/maybach/white",
  "Mazda": "https://cdn.simpleicons.org/mazda/white",
  "McLaren": "https://cdn.simpleicons.org/mclaren/white",
  "Mercedes-Benz": "https://cdn.simpleicons.org/mercedes/white",
  "MG": "https://cdn.simpleicons.org/mg/white",
  "Mini": "https://cdn.simpleicons.org/mini/white",
  "MINI": "https://cdn.simpleicons.org/mini/white",
  "Mitsubishi": "https://cdn.simpleicons.org/mitsubishi/white",
  "Nio": "https://cdn.simpleicons.org/nio/white",
  "NIO": "https://cdn.simpleicons.org/nio/white",
  "Nissan": "https://cdn.simpleicons.org/nissan/white",
  "Opel": "https://cdn.simpleicons.org/opel/white",
  "OMODA": "https://cdn.simpleicons.org/omoda/white",
  "Omoda": "https://cdn.simpleicons.org/omoda/white",
  "Pagani": "https://cdn.simpleicons.org/pagani/white",
  "Peugeot": "https://cdn.simpleicons.org/peugeot/white",
  "Polestar": "https://cdn.simpleicons.org/polestar/white",
  "Pontiac": "https://cdn.simpleicons.org/pontiac/white",
  "Porsche": "https://cdn.simpleicons.org/porsche/white",
  "RAM": "https://cdn.simpleicons.org/ram/white",
  "Ram": "https://cdn.simpleicons.org/ram/white",
  "Renault": "https://cdn.simpleicons.org/renault/white",
  "Rolls-Royce": "https://cdn.simpleicons.org/rollsroyce/white",
  "Saab": "https://cdn.simpleicons.org/saab/white",
  "SEAT": "https://cdn.simpleicons.org/seat/white",
  "Seat": "https://cdn.simpleicons.org/seat/white",
  "Skoda": "https://cdn.simpleicons.org/skoda/white",
  "Škoda": "https://cdn.simpleicons.org/skoda/white",
  "Smart": "https://cdn.simpleicons.org/smart/white",
  "Subaru": "https://cdn.simpleicons.org/subaru/white",
  "Suzuki": "https://cdn.simpleicons.org/suzuki/white",
  "Tank": "https://cdn.simpleicons.org/tank/white",
  "Tesla": "https://cdn.simpleicons.org/tesla/white",
  "Toyota": "https://cdn.simpleicons.org/toyota/white",
  "Volkswagen": "https://cdn.simpleicons.org/volkswagen/white",
  "Volvo": "https://cdn.simpleicons.org/volvo/white",
  "Voyah": "https://cdn.simpleicons.org/voyah/white",
  "WEY": "https://cdn.simpleicons.org/wey/white",
  "Wey": "https://cdn.simpleicons.org/wey/white",
  "XPENG": "https://cdn.simpleicons.org/xpeng/white",
  "Xpeng": "https://cdn.simpleicons.org/xpeng/white",
  "Zeekr": "https://cdn.simpleicons.org/zeekr/white",
  "ZEEKR": "https://cdn.simpleicons.org/zeekr/white"
};
