const ALL_BRANDS = [
  { name: 'Abarth', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/abarth' , page: 'abarth.html'},
  { name: 'Acura', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/acura' },
  { name: 'Aixam', country: 'Франция', region: 'Швеция/Франция', status: 'active' },
  { name: 'Alfa Romeo', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/alfaromeo' },
  { name: 'Alpina', country: 'Германия', region: 'Германия', status: 'active' },
  { name: 'Alpine', country: 'Франция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/alpine' },
  { name: 'AMC', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Ariel', country: 'Великобритания', region: 'Великобритания', status: 'active' },
  { name: 'Aro', country: 'Румыния', region: 'Европа', status: 'defunct' },
  { name: 'Aston Martin', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/astonmartin' },
  { name: 'Audi', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/audi' },
  { name: 'Aurus', country: 'Россия', region: 'Россия/СНГ', status: 'active'  },
  { name: 'Austin', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Autobianchi', country: 'Италия', region: 'Италия', status: 'defunct' },
  { name: 'Avatr', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Baojun', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'BAIC', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Bentley', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/bentley' },
  { name: 'Bestune', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Bizzarrini', country: 'Италия', region: 'Италия', status: 'active' },
  { name: 'BMC', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'BMW', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/bmw' },
  { name: 'Borgward', country: 'Германия', region: 'Германия', status: 'active'  },
  { name: 'Brabus', country: 'Германия', region: 'Германия', status: 'active'  },
  { name: 'Brilliance', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Buick', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/buick' },
  { name: 'BYD', country: 'Китай', region: 'Китай', status: 'active' , logo: 'https://cdn.simpleicons.org/byd' },
  { name: 'Cadillac', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/cadillac' },
  { name: 'Caterham', country: 'Великобритания', region: 'Великобритания', status: 'active' },
  { name: 'Changan', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Changhe', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Chery', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Chevrolet', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/chevrolet' },
  { name: 'Chrysler', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/chrysler' },
  { name: 'Citroen', country: 'Франция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/citroen' },
  { name: 'Cizeta', country: 'Италия', region: 'Италия', status: 'defunct' },
  { name: 'Cupra', country: 'Испания', region: 'Европа', status: 'active' , logo: 'https://cdn.simpleicons.org/cupra' },
  { name: 'Dacia', country: 'Румыния', region: 'Европа', status: 'active' , logo: 'https://cdn.simpleicons.org/dacia' },
  { name: 'Daewoo', country: 'Корея', region: 'Корея', status: 'defunct'  },
  { name: 'DAF', country: 'Нидерланды', region: 'Европа', status: 'defunct' },
  { name: 'Daihatsu', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/daihatsu' },
  { name: 'Datsun', country: 'Япония', region: 'Япония', status: 'defunct' , logo: 'https://cdn.simpleicons.org/datsun' },
  { name: 'DeLorean', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Denza', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Dodge', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/dodge' },
  { name: 'Dongfeng', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'DS Automobiles', country: 'Франция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/dsautomobiles' },
  { name: 'Eagle', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Exeed', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'FAW', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Ferrari', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/ferrari' },
  { name: 'Fiat', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/fiat' },
  { name: 'Fisker', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/fisker' },
  { name: 'Ford', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/ford' },
  { name: 'Foton', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'GAZ', country: 'Россия', region: 'Россия/СНГ', status: 'active'  },
  { name: 'Geely', country: 'Китай', region: 'Китай', status: 'active' , logo: 'https://cdn.simpleicons.org/geely' },
  { name: 'Genesis', country: 'Корея', region: 'Корея', status: 'active' , logo: 'https://cdn.simpleicons.org/genesis' },
  { name: 'GMC', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/gmc' },
  { name: 'Great Wall', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Hafei', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Haima', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Haval', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Hindustan', country: 'Индия', region: 'Индия/Азия', status: 'defunct' },
  { name: 'Holden', country: 'Австралия', region: 'Австралия', status: 'defunct' },
  { name: 'Honda', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/honda' },
  { name: 'Hongqi', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Hummer', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/hummer' },
  { name: 'Hyundai', country: 'Корея', region: 'Корея', status: 'active' , logo: 'https://cdn.simpleicons.org/hyundai' },
  { name: 'Ineos', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/ineos' },
  { name: 'Infiniti', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/infiniti' },
  { name: 'Iran Khodro', country: 'Иран', region: 'Ближний Восток', status: 'active' },
  { name: 'Isdera', country: 'Германия', region: 'Германия', status: 'active' },
  { name: 'Isuzu', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/isuzu' },
  { name: 'JAC', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Jaguar', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/jaguar' },
  { name: 'Jeep', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/jeep' },
  { name: 'Jetour', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Jetta', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Jinbei', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Kaiyi', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Karma', country: 'США', region: 'США', status: 'active' },
  { name: 'Kia', country: 'Корея', region: 'Корея', status: 'active' , logo: 'https://cdn.simpleicons.org/kia' },
  { name: 'Koenigsegg', country: 'Швеция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/koenigsegg' },
  { name: 'Lada', country: 'Россия', region: 'Россия/СНГ', status: 'active', page: 'lada.html' , logo: 'https://cdn.simpleicons.org/lada' },
  { name: 'Lagonda', country: 'Великобритания', region: 'Великобритания', status: 'active' },
  { name: 'Lamborghini', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/lamborghini' },
  { name: 'Lancia', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/lancia' },
  { name: 'Land Rover', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/landrover' },
  { name: 'Leapmotor', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Lexus', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/lexus' },
  { name: 'Li Auto', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Lifan', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Lincoln', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/lincoln' },
  { name: 'Lotus', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/lotus' },
  { name: 'Lucid', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/lucid' },
  { name: 'Luxgen', country: 'Тайвань', region: 'Индия/Азия', status: 'active' },
  { name: 'Lynk & Co', country: 'Китай', region: 'Китай', status: 'active' , logo: 'https://cdn.simpleicons.org/lynkco' },
  { name: 'Mahindra', country: 'Индия', region: 'Индия/Азия', status: 'active' , logo: 'https://cdn.simpleicons.org/mahindra' },
  { name: 'Maserati', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/maserati' },
  { name: 'Maybach', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/maybach' },
  { name: 'Mazda', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/mazda' },
  { name: 'McLaren', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/mclaren' },
  { name: 'Mercedes-Benz', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/mercedes' },
  { name: 'Mercury', country: 'США', region: 'США', status: 'defunct' },
  { name: 'MG', country: 'Великобритания/Китай', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/mg' },
  { name: 'Mini', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/mini' },
  { name: 'Mitsubishi', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/mitsubishi' },
  { name: 'Moskvich', country: 'Россия', region: 'Россия/СНГ', status: 'active'  },
  { name: 'Neta', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Nio', country: 'Китай', region: 'Китай', status: 'active' , logo: 'https://cdn.simpleicons.org/nio' },
  { name: 'Nissan', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/nissan' },
  { name: 'Oldsmobile', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Omoda', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Opel', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/opel' },
  { name: 'Ora', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Pagani', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/pagani' },
  { name: 'Panoz', country: 'США', region: 'США', status: 'active' },
  { name: 'Peugeot', country: 'Франция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/peugeot' },
  { name: 'Plymouth', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Polestar', country: 'Швеция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/polestar' },
  { name: 'Pontiac', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Porsche', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/porsche' },
  { name: 'Proton', country: 'Малайзия', region: 'Индия/Азия', status: 'active' , logo: 'https://cdn.simpleicons.org/proton' },
  { name: 'Qoros', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'RAM', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/ram' },
  { name: 'Renault', country: 'Франция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/renault' },
  { name: 'Rimac', country: 'Хорватия', region: 'Европа', status: 'active' , logo: 'https://cdn.simpleicons.org/rimac' },
  { name: 'Rivian', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/rivian' },
  { name: 'Rolls-Royce', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/rollsroyce' },
  { name: 'Rover', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Saab', country: 'Швеция', region: 'Швеция/Франция', status: 'defunct' , logo: 'https://cdn.simpleicons.org/saab' },
  { name: 'Saturn', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Scion', country: 'Япония/США', region: 'Япония', status: 'defunct' },
  { name: 'Seat', country: 'Испания', region: 'Европа', status: 'active' , logo: 'https://cdn.simpleicons.org/seat' },
  { name: 'Seres', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Shuanghuan', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Skoda', country: 'Чехия', region: 'Европа', status: 'active' , logo: 'https://cdn.simpleicons.org/skoda' },
  { name: 'Smart', country: 'Германия/Китай', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/smart' },
  { name: 'Sollers', country: 'Россия', region: 'Россия/СНГ', status: 'active'  },
  { name: 'Soueast', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Spyker', country: 'Нидерланды', region: 'Европа', status: 'active' },
  { name: 'SsangYong', country: 'Корея', region: 'Корея', status: 'defunct'  },
  { name: 'Subaru', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/subaru' },
  { name: 'Suzuki', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/suzuki' },
  { name: 'Tata', country: 'Индия', region: 'Индия/Азия', status: 'active' , logo: 'https://cdn.simpleicons.org/tata' },
  { name: 'Tatra', country: 'Чехия', region: 'Европа', status: 'active' },
  { name: 'Tesla', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/tesla' },
  { name: 'Toyota', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/toyota' },
  { name: 'Trabant', country: 'ГДР', region: 'Европа', status: 'defunct' },
  { name: 'TVR', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/tvr' },
  { name: 'UAZ', country: 'Россия', region: 'Россия/СНГ', status: 'active'  },
  { name: 'Vauxhall', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/vauxhall' },
  { name: 'Vector', country: 'США', region: 'США', status: 'defunct' },
  { name: 'VinFast', country: 'Вьетнам', region: 'Индия/Азия', status: 'active' , logo: 'https://cdn.simpleicons.org/vinfast' },
  { name: 'Volkswagen', country: 'Германия', region: 'Германия', status: 'active' , logo: 'https://cdn.simpleicons.org/volkswagen' },
  { name: 'Volvo', country: 'Швеция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/volvo' },
  { name: 'Voyah', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Wartburg', country: 'ГДР', region: 'Европа', status: 'defunct' },
  { name: 'Wey', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Wiesmann', country: 'Германия', region: 'Германия', status: 'active' },
  { name: 'Wuling', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Xiaomi Auto', country: 'Китай', region: 'Китай', status: 'active' , logo: 'https://cdn.simpleicons.org/xiaomi' },
  { name: 'XPeng', country: 'Китай', region: 'Китай', status: 'active' , logo: 'https://cdn.simpleicons.org/xpeng' },
  { name: 'Zeekr', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Zotye', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Adler', country: 'Германия', region: 'Германия', status: 'defunct' },
  { name: 'Aion', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Allard', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'American Motors', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Aptera', country: 'США', region: 'США', status: 'active' },
  { name: 'Ascari', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Askam', country: 'Турция', region: 'Ближний Восток', status: 'defunct' },
  { name: 'Aspark', country: 'Япония', region: 'Япония', status: 'active' },
  { name: 'BAW', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Barkas', country: 'ГДР', region: 'Европа', status: 'defunct' },
  { name: 'Bristol', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Bitter', country: 'Германия', region: 'Германия', status: 'active' },
  { name: 'Bollore', country: 'Франция', region: 'Швеция/Франция', status: 'active' },
  { name: 'Brezza', country: 'Индия', region: 'Индия/Азия', status: 'active' },
  { name: 'Canoo', country: 'США', region: 'США', status: 'active' },
  { name: 'Caparo', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Carlsson', country: 'Германия', region: 'Германия', status: 'active' },
  { name: 'Casalini', country: 'Италия', region: 'Италия', status: 'active' },
  { name: 'Cenntro', country: 'США', region: 'США', status: 'active' },
  { name: 'ChangAn Nevo', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Coda', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Dallara', country: 'Италия', region: 'Италия', status: 'active' },
  { name: 'Denza N7', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Detroit Electric', country: 'США', region: 'США', status: 'active' },
  { name: 'Dino', country: 'Италия', region: 'Италия', status: 'defunct' },
  { name: 'Elfin', country: 'Австралия', region: 'Австралия', status: 'active' },
  { name: 'Englon', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Eterniti', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Everus', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Faraday Future', country: 'США', region: 'США', status: 'active' },
  { name: 'Force Motors', country: 'Индия', region: 'Индия/Азия', status: 'active' },
  { name: 'FSO', country: 'Польша', region: 'Европа', status: 'defunct' },
  { name: 'GAC', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Ginetta', country: 'Великобритания', region: 'Великобритания', status: 'active' },
  { name: 'Gonow', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Hispano-Suiza', country: 'Испания', region: 'Европа', status: 'active' },
  { name: 'Hudson', country: 'США', region: 'США', status: 'defunct' },
  { name: 'IM Motors', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Imperial', country: 'США', region: 'США', status: 'defunct' },
  { name: 'International', country: 'США', region: 'США', status: 'active' },
  { name: 'Invicta', country: 'Великобритания', region: 'Великобритания', status: 'active' },
  { name: 'Jawa', country: 'Чехия', region: 'Европа', status: 'active' },
  { name: 'Jidu', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Lobini', country: 'Бразилия', region: 'Латинская Америка', status: 'active' },
  { name: 'Marcos', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Maruti Suzuki', country: 'Индия', region: 'Индия/Азия', status: 'active' , logo: 'https://cdn.simpleicons.org/marutisuzuki' },
  { name: 'Matra', country: 'Франция', region: 'Швеция/Франция', status: 'defunct' },
  { name: 'Mazzanti', country: 'Италия', region: 'Италия', status: 'active' },
  { name: 'Melkus', country: 'Германия', region: 'Германия', status: 'defunct' },
  { name: 'Mercer', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Mitsuoka', country: 'Япония', region: 'Япония', status: 'active' , logo: 'https://cdn.simpleicons.org/mitsuoka' },
  { name: 'Mosler', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Noble', country: 'Великобритания', region: 'Великобритания', status: 'active' , logo: 'https://cdn.simpleicons.org/noble' },
  { name: 'NSU', country: 'Германия', region: 'Германия', status: 'defunct' },
  { name: 'Old Yugo', country: 'Югославия', region: 'Европа', status: 'defunct' },
  { name: 'Peking Jeep', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Perodua', country: 'Малайзия', region: 'Индия/Азия', status: 'active' , logo: 'https://cdn.simpleicons.org/perodua' },
  { name: 'Pininfarina', country: 'Италия', region: 'Италия', status: 'active' , logo: 'https://cdn.simpleicons.org/pininfarina' },
  { name: 'Puma', country: 'Бразилия', region: 'Латинская Америка', status: 'active' },
  { name: 'Radical', country: 'Великобритания', region: 'Великобритания', status: 'active' },
  { name: 'Reliant', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Rezvani', country: 'США', region: 'США', status: 'active'  },
  { name: 'Roewe', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'Rossion', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Saleen', country: 'США', region: 'США', status: 'active' , logo: 'https://cdn.simpleicons.org/saleen' },
  { name: 'Scania', country: 'Швеция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/scania' },
  { name: 'Shelby', country: 'США', region: 'США', status: 'active'  },
  { name: 'Sin Cars', country: 'Болгария', region: 'Европа', status: 'active' },
  { name: 'SRT', country: 'США', region: 'США', status: 'active' },
  { name: 'Steyr', country: 'Австрия', region: 'Европа', status: 'defunct' },
  { name: 'Studebaker', country: 'США', region: 'США', status: 'defunct' },
  { name: 'Talbot', country: 'Франция', region: 'Швеция/Франция', status: 'defunct' },
  { name: 'Tianjin', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Tofas', country: 'Турция', region: 'Ближний Восток', status: 'active' },
  { name: 'Triumph', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Venturi', country: 'Франция', region: 'Швеция/Франция', status: 'active' , logo: 'https://cdn.simpleicons.org/venturi' },
  { name: 'Venucia', country: 'Китай', region: 'Китай', status: 'active'  },
  { name: 'W Motors', country: 'ОАЭ', region: 'Ближний Восток', status: 'active'  },
  { name: 'Westfield', country: 'Великобритания', region: 'Великобритания', status: 'active'  },
  { name: 'Xin Kai', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Yema', country: 'Китай', region: 'Китай', status: 'defunct' },
  { name: 'Yulon', country: 'Тайвань', region: 'Индия/Азия', status: 'active' },
  { name: 'Zenos', country: 'Великобритания', region: 'Великобритания', status: 'defunct' },
  { name: 'Zhidou', country: 'Китай', region: 'Китай', status: 'active' },
  { name: 'Zimmer', country: 'США', region: 'США', status: 'active'  },
  { name: 'Zundapp Janus', country: 'Германия', region: 'Германия', status: 'defunct' },
  { name: 'Arcfox', country: 'Разные страны', region: 'Прочее', status: 'active'  },
  { name: 'Aito', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Aiways', country: 'Разные страны', region: 'Прочее', status: 'active'  },
  { name: 'Bisu', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Cowin', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Dayun', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Deepal', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Enovate', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Forthing', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Geometry', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Hawtai', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'HiPhi', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'JMC', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Levc', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Maple', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Maxus', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Nanjing', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Naza', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Nissan-Datsun', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Qvale', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Ruf', country: 'Разные страны', region: 'Прочее', status: 'active'  },
  { name: 'Shacman', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Skywell', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Togg', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Troller', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Vencer', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'WEVC', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Yudo', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'ZXAUTO', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Ebro', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Torc', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Hozon', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Onvo', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Aehra', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'BharatBenz', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'FAW Bestune', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Nami', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Yangwang', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Fangchengbao', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Riddara', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Jiyue', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'IM', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Exlantix', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Sollers Atlant', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Solaris', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Saturn Sky', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'Puch', country: 'Разные страны', region: 'Прочее', status: 'active' },
  { name: 'RAM SRT-10', country: 'Разные страны', region: 'Прочее', status: 'active' },
];

window.ALL_BRANDS = ALL_BRANDS;
