// Карта логотипов брендов для Autobase
// Ключ должен совпадать с полем name в brands.js

const BRAND_LOGOS = {
  "Abarth": "https://cdn.simpleicons.org/abarth/ffffff",
  "Acura": "https://cdn.simpleicons.org/acura/ffffff",
  "Alfa Romeo": "https://cdn.simpleicons.org/alfaromeo/ffffff",
  "Alpine": "https://cdn.simpleicons.org/alpine/ffffff",
  "Aston Martin": "https://cdn.simpleicons.org/astonmartin/ffffff",
  "Audi": "https://cdn.simpleicons.org/audi/ffffff",
  "BAIC": "https://cdn.simpleicons.org/baic/ffffff",
  "Bentley": "https://cdn.simpleicons.org/bentley/ffffff",
  "BMW": "https://cdn.simpleicons.org/bmw/ffffff",
  "Bugatti": "https://cdn.simpleicons.org/bugatti/ffffff",
  "Buick": "https://cdn.simpleicons.org/buick/ffffff",
  "BYD": "https://cdn.simpleicons.org/byd/ffffff",
  "Cadillac": "https://cdn.simpleicons.org/cadillac/ffffff",
  "Chevrolet": "https://cdn.simpleicons.org/chevrolet/ffffff",
  "Chery": "https://cdn.simpleicons.org/chery/ffffff",
  "Chrysler": "https://cdn.simpleicons.org/chrysler/ffffff",
  "Citroen": "https://cdn.simpleicons.org/citroen/ffffff",
  "Cupra": "https://cdn.simpleicons.org/cupra/ffffff",
  "Dacia": "https://cdn.simpleicons.org/dacia/ffffff",
  "Daewoo": "https://cdn.simpleicons.org/daewoo/ffffff",
  "Daihatsu": "https://cdn.simpleicons.org/daihatsu/ffffff",
  "Dodge": "https://cdn.simpleicons.org/dodge/ffffff",
  "DS": "https://cdn.simpleicons.org/dsautomobiles/ffffff",
  "Ferrari": "https://cdn.simpleicons.org/ferrari/ffffff",
  "Fiat": "https://cdn.simpleicons.org/fiat/ffffff",
  "Ford": "https://cdn.simpleicons.org/ford/ffffff",
  "Genesis": "https://cdn.simpleicons.org/genesis/ffffff",
  "GMC": "https://cdn.simpleicons.org/gmc/ffffff",
  "Honda": "https://cdn.simpleicons.org/honda/ffffff",
  "Hummer": "https://cdn.simpleicons.org/hummer/ffffff",
  "Hyundai": "https://cdn.simpleicons.org/hyundai/ffffff",
  "Infiniti": "https://cdn.simpleicons.org/infiniti/ffffff",
  "Isuzu": "https://cdn.simpleicons.org/isuzu/ffffff",
  "Jaguar": "https://cdn.simpleicons.org/jaguar/ffffff",
  "Jeep": "https://cdn.simpleicons.org/jeep/ffffff",
  "Kia": "https://cdn.simpleicons.org/kia/ffffff",
  "Koenigsegg": "https://cdn.simpleicons.org/koenigsegg/ffffff",
  "Lada (ВАЗ)": "https://cdn.simpleicons.org/lada/ffffff",
  "Lamborghini": "https://cdn.simpleicons.org/lamborghini/ffffff",
  "Lancia": "https://cdn.simpleicons.org/lancia/ffffff",
  "Land Rover": "https://cdn.simpleicons.org/landrover/ffffff",
  "Lexus": "https://cdn.simpleicons.org/lexus/ffffff",
  "Lincoln": "https://cdn.simpleicons.org/lincoln/ffffff",
  "Lotus": "https://cdn.simpleicons.org/lotus/ffffff",
  "Maserati": "https://cdn.simpleicons.org/maserati/ffffff",
  "Maybach": "https://cdn.simpleicons.org/maybach/ffffff",
  "Mazda": "https://cdn.simpleicons.org/mazda/ffffff",
  "McLaren": "https://cdn.simpleicons.org/mclaren/ffffff",
  "Mercedes-Benz": "https://cdn.simpleicons.org/mercedes/ffffff",
  "MG": "https://cdn.simpleicons.org/mg/ffffff",
  "Mini": "https://cdn.simpleicons.org/mini/ffffff",
  "Mitsubishi": "https://cdn.simpleicons.org/mitsubishi/ffffff",
  "Nissan": "https://cdn.simpleicons.org/nissan/ffffff",
  "Opel": "https://cdn.simpleicons.org/opel/ffffff",
  "Pagani": "https://cdn.simpleicons.org/pagani/ffffff",
  "Peugeot": "https://cdn.simpleicons.org/peugeot/ffffff",
  "Polestar": "https://cdn.simpleicons.org/polestar/ffffff",
  "Pontiac": "https://cdn.simpleicons.org/pontiac/ffffff",
  "Porsche": "https://cdn.simpleicons.org/porsche/ffffff",
  "Ram": "https://cdn.simpleicons.org/ram/ffffff",
  "Renault": "https://cdn.simpleicons.org/renault/ffffff",
  "Rolls-Royce": "https://cdn.simpleicons.org/rollsroyce/ffffff",
  "Saab": "https://cdn.simpleicons.org/saab/ffffff",
  "SEAT": "https://cdn.simpleicons.org/seat/ffffff",
  "Skoda": "https://cdn.simpleicons.org/skoda/ffffff",
  "Smart": "https://cdn.simpleicons.org/smart/ffffff",
  "Subaru": "https://cdn.simpleicons.org/subaru/ffffff",
  "Suzuki": "https://cdn.simpleicons.org/suzuki/ffffff",
  "Tesla": "https://cdn.simpleicons.org/tesla/ffffff",
  "Toyota": "https://cdn.simpleicons.org/toyota/ffffff",
  "Volkswagen": "https://cdn.simpleicons.org/volkswagen/ffffff",
  "Volvo": "https://cdn.simpleicons.org/volvo/ffffff",
  "XPENG": "https://cdn.simpleicons.org/xpeng/ffffff",
  "Zeekr": "https://cdn.simpleicons.org/zeekr/ffffff"
};
